### ISSUE TITLE
Bug: Mulitselect of 7+ children is Extremely slow in Ore 3d

### ISSUE THREAD

**Issue by orepf** [Ore-Design/Ore-3D-Reports-Changelog#467] opened 2023-04-11 15:53 UTC
When selecting multiple children to change a finish or material ORE 3D slows down really bad. We need to be able to select up to at least 100 with no problems

**Comment by Reyzerbit** [comment] 2023-04-11 16:02
Duplicate of #458

**Closed by Reyzerbit** 2023-04-11 16:02 UTC
Labels: bug
