### ISSUE TITLE
Bug: Fuse Split [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#112] opened 2022-11-22 15:59 UTC
Crashes on split.

Recover estimate shows that the split is there. 

***MATERIAL AND LIPS RESET AT SPLIT***

**Comment by Reyzerbit** [comment] 2022-11-22 16:18
Duplicate of #103

**Closed by Reyzerbit** 2022-11-22 16:18 UTC
Labels: bug
