### ISSUE TITLE
Feature: Blinking Bar Text

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#370] opened 2023-03-13 15:06 UTC
Can you add the blinking bar to show what field is selected and where text will be typed? It seems to show up in some places, but not otherers.

Internal Notes shows the blinking bar, but Customer Notes does not. 

Fields in the Right Panel generally do not show the blinking bar.

**Comment by Reyzerbit** [comment] 2023-03-14 16:42
Duplicate of #339

**Closed by Reyzerbit** 2023-03-14 16:42 UTC
Labels: enhancement
