### ISSUE TITLE
Bug: ADDING A CUSTOM COMPONENT CRASHES ORE3D

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#503] opened 2023-04-26 16:55 UTC
CRASHED FOR JOSH AND I

**Comment by Reyzerbit** [comment] 2023-04-26 23:42
Duplicate of #502

**Closed by Reyzerbit** 2023-04-26 23:42 UTC
Labels: bug

**Comment by daniel11088** [comment] 2023-04-27 13:35
What's the time frame on getting this resolved?
