### ISSUE TITLE
Bug: Raised Lid Margin [Ore3D Version (1.9.3)]

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore-3D-Reports-Changelog#621] opened 2023-06-12 18:58 UTC
**Bug:**
Raised Lids are margined in Ore3D instead of cost being expected total price. Margin is supposed to be 0 Just like other lid types
![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/133701810/c02676bd-5763-4d45-a8e2-7aee5e2d7c74)

**Comment by Reyzerbit** [comment] 2023-06-12 19:25
Duplicate of #611

**Closed by Reyzerbit** 2023-06-12 19:25 UTC
Labels: bug
