### ISSUE TITLE
Reveal type is wrong on standards

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#881] opened 2024-02-20 20:03 UTC
The reveal type is showing up wrong on most standard items.

EX: 

A1110 is showing up as a skirt but if we change it to a skid it moves it to custom which increases the price.

Netsuite is showing that it should read as a skid so where is ORE3D pulling reveal type?

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/e7022150-40da-49ea-bc18-c14411abc01f)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/1a7878c6-b23d-4bd8-b122-dca60c2e86fb)

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/a0506a9c-4aed-4ac5-b00e-4f5829fab62a)

**Comment by Reyzerbit** [comment] 2024-02-22 20:14
duplicate of [Ore3D Internal #1](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/issues/1)

**Closed by Reyzerbit** 2024-02-22 20:14 UTC
Labels: bug
