### ISSUE TITLE
Bug: CRASH after save

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#391] opened 2023-03-13 21:54 UTC
CRASH:

After save:
-Return to order>crash
-Finish>[reopen proposal that I was in]>crash

-reopen Ore3D>load last proposal (not the auto save feature)>crash
-It will open using the auto saved data

**Comment by Reyzerbit** [comment] 2023-03-14 16:54
Duplicate of #382

**Closed by Reyzerbit** 2023-03-14 16:54 UTC
Labels: bug
