### ISSUE TITLE
Bug: Add BOM Item (thats fabricated)

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#605] opened 2023-06-07 17:07 UTC
Example: Drip Tray

When you add a drip tray without a planter there is no option to specify a powder coat & there are not visible routings/BOM for this item.

Solution will likely need to be coordinated with J.Drake & M.Israel

**Comment by Reyzerbit** [comment] 2023-06-07 17:15
Duplicate of #583

**Closed by Reyzerbit** 2023-06-07 17:15 UTC
Labels: bug
