### ISSUE TITLE
Bug: More characters in Customer Notes needed

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#570] opened 2023-05-24 16:33 UTC
Can we increase the number of characters in the customer notes field?

I thought it was being raised to 500?

**Comment by Reyzerbit** [comment] 2023-05-24 16:57
Duplicate of #563. Please direct further questions regarding this limitation to @mxidis.

**Closed by Reyzerbit** 2023-05-24 16:57 UTC
Labels: bug
