### ISSUE TITLE
UI Feature: Reformat BOM Sub Total

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#980] opened 2024-04-08 16:34 UTC
Please move the BOM subtotal to above 'children'. 

BOM subtotal= 'default BOM' + add on options(ex. df, irr).

EXCLUDED FROM BOM SUBTOTAL:
-Children (drip trays, lids, etc)
~~-Misc Charges~~ Already excluded from BOM subtotal

![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114440644/3193e1a2-d9ab-44e6-8850-d3b50147c723)

**Comment by mxidis** [comment] 2024-04-09 20:05
Why?

**Comment by MattIsrael** [comment] 2024-04-09 20:21
We need to be able to view the price (BOM & Routings) for the 'base element'(parent) completely separate from any children that are rolling up into the 'parent'. 

- I believe this is the topic of discussion in today's bug squashers
-

**Comment by Reyzerbit** [comment] 2024-04-09 21:47
Duplicate of #984

**Closed by Reyzerbit** 2024-04-09 21:47 UTC
Labels: enhancement, low priority
