### ISSUE TITLE
Other: Netsuite Description Reformat - Fuse

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#154] opened 2022-12-09 22:01 UTC
[Label]
[L" (LF if edging)] x [width"] x [height"]H [product*] [[material gauge"]]; [Finish Type]: [Specific Finish]
[Custom Description]

Perimeter Edging
794LF x 14"W x 33"H Unanchored Aluminum Linear FuSE Retention Edging [.25", ]; Powder Coat Finish: TBD

Product* (maybe shape code in Ore3D?)
-Linear Fuse Planter
-Curved Fuse Planter
-Linear Fuse Retention Edging - Anchored/Un-Anchored
-Curved Fuse Retention Edging - Anchored/Un-Anchored

**Comment by Reyzerbit** [comment] 2022-12-13 16:29
Closed as duplicate of #129

**Closed by Reyzerbit** 2022-12-13 16:29 UTC
