### ISSUE TITLE
Bug: Crash on Abstract Build Add to Order [Ore3D Version (1.4.1 etc)]

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#215] opened 2023-01-03 20:20 UTC
![image](https://user-images.githubusercontent.com/114440644/210435039-db19550b-558b-4247-98d8-e68104061c01.png)

**Comment by Reyzerbit** [comment] 2023-01-03 21:48
Caused by same issue as #197 , will be fixed in 1.6.2

**Closed by Reyzerbit** 2023-01-03 21:48 UTC
Labels: bug
