### ISSUE TITLE
More Character types in Ore3D and Netsuite

### ISSUE THREAD

**Issue by CBarsell** [Ore-Design/Ore-3D-Reports-Changelog#739] opened 2023-11-08 15:48 UTC
We have noticed there's a lot of characters that get changed to "?" after saving the proposal. it shows in netsuite as well. Sometimes it seems that netsuite only gets the "?" and Ore3D still displays the correct character after saving. If we could get a bigger character library that would make things a little bit better for everyone

**Comment by Reyzerbit** [comment] 2023-12-12 20:24
Will be resolved with rewrite. This limitation is caused by Unity, so the move to Java will resolve this on its own.

**Closed by Reyzerbit** 2023-12-12 20:24 UTC
Labels: enhancement
