### ISSUE TITLE
Bug: UI Build Tiles are Multiplied on Add

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#932] opened 2024-03-18 18:18 UTC
![image](https://github.com/Ore-Design/Ore3DInternal-Reports-Changelog/assets/114690243/4c78b501-73f4-4ee8-a858-2cd1dd5db74d)

**Comment by Reyzerbit** [comment] 2024-03-19 15:34
Duplicate of #924

**Closed by Reyzerbit** 2024-03-19 15:34 UTC
Labels: bug
