### ISSUE TITLE
Feature: Clean up Results of Add General Product

### ISSUE THREAD

**Issue by MattIsrael** [Ore-Design/Ore-3D-Reports-Changelog#232] opened 2023-01-09 21:34 UTC
The results of some 'general products' is quite lengthy due to different materials/finishes being listed as unique part #s. [bison is really bad]

Can we add filters that would sort by material (prefix) or finish type (sufix)? Maybe a couple drop down menus near the search bar? I'm open to discussing how this would look.

![image](https://user-images.githubusercontent.com/114440644/211412616-288fba67-ec49-4af0-aa62-e43e3e4b6a5b.png)

**Comment by Reyzerbit** [comment] 2023-01-13 22:07
Closed as already implemented with the search bar. If the search bar doesn't behave as intended let me know, but there are no plans fro additional buttons/dropdowns on this menu at this time, in favor of the search bar.

**Closed by Reyzerbit** 2023-01-13 22:07 UTC
Labels: enhancement
