### ISSUE TITLE
Routings not mathing

### ISSUE THREAD

**Issue by daniel11088** [Ore-Design/Ore-3D-Reports-Changelog#1019] opened 2024-04-26 19:03 UTC
Routings are not adding.
No subtotal on Pre-design or Modified.

![image](https://github.com/Ore-Design/Ore-3D-Reports-Changelog/assets/114690243/80c0c08a-18cc-48c6-ae59-a3b26e98245d)

**Comment by Reyzerbit** [comment] 2024-04-26 19:05
Duplicate of #1017

**Closed by Reyzerbit** 2024-04-26 19:05 UTC
Labels: bug
