### ISSUE TITLE
Bug: ORE 3D crashes when adding any component.

### ISSUE THREAD

**Issue by jjohnson2525** [Ore-Design/Ore-3D-Reports-Changelog#511] opened 2023-04-27 14:04 UTC
**Bug:**
ORE 3D crashes when adding any component.

**Recreate:**
1. Add 1110
2. Navigate to receipt panel 
3. Click Add Item

**Comment by Reyzerbit** [comment] 2023-04-27 14:52
Duplicate of #504

**Closed by Reyzerbit** 2023-04-27 14:52 UTC
Labels: bug
